#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Lotus.Resource", IsApplication=true)]

namespace Lotus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int game1_in = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int game2_in = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int maintext_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int poem_change = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int zoom_in = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int zoom_out = 2130968581;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int back_pressed = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backButton = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bg1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bg2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg2_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg4_pressed = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int car_cover = 2130837513;
			
			// aapt resource value: 0x7f020090
			public const int clr1_normal = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int clr2_normal = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int clr3_normal = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int clr4_normal = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int clr_pressed = 2130837652;
			
			// aapt resource value: 0x7f02000a
			public const int drawing1 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int drawing2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int drawing3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int drawing4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int drawing5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int drawing6 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int drawing7 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int food1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int food2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int food3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int food4 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int food5 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int food6 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int food7 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int food8 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int foodButton_selector = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int game1_1 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int game1_2 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int game1_3 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int game1_4 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int game1_5 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int game1_6 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int game1_7 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int game1_8 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int game1_9 = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int game1_ali = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int gamebg = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int gamelogo1 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int gamelogo2 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int Icon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int label = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int label1 = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int label2 = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int label3 = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int label4 = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int labelsetting = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int logo1_button1_selector = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int logo1_button2_selector = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int logo1_button3_selector = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int logo1_button4_selector = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int logo1_pressed = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int logo1_up = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int logo1Button = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int logo2_pressed = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int logo2_up = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int logo2Button = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int logo3_pressed = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int logo3_up = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int logo3Button = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int logo4_pressed = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int logo4_up = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int logo4Button = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int LogoButtonBg = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int loli1 = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int loli10 = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int loli11 = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int loli12 = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int loli13 = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int loli14 = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int loli15 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int loli16 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int loli17 = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int loli18 = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int loli19 = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int loli2 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int loli20 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int loli21 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int loli22 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int loli23 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int loli24 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int loli25 = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int loli26 = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int loli27 = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int loli3 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int loli4 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int loli5 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int loli6 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int loli7 = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int loli8 = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int loli9 = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int lotus1_1 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int lotus1_10 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int lotus1_11 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int lotus1_12 = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int lotus1_13 = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int lotus1_14 = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int lotus1_15 = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int lotus1_16 = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int lotus1_17 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int lotus1_18 = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int lotus1_19 = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int lotus1_2 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int lotus1_20 = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int lotus1_3 = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int lotus1_4 = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int lotus1_5 = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int lotus1_6 = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int lotus1_7 = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int lotus1_8 = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int lotus1_9 = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int lotus2_1 = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int lotus2_10 = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int lotus2_2 = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int lotus2_3 = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int lotus2_4 = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int lotus2_5 = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int lotus2_6 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int lotus2_7 = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int lotus2_8 = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int lotus2_9 = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int lotus3_1 = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int lotus3_2 = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int lotus3_3 = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int lotus3_4 = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int lotus3_5 = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int lotuscarLogo = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int lotusmann_logo = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int lotusmannCover = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int mainbg3 = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int mainpic1 = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int mainpic2 = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int mainpic3 = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int mainpic4 = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int mainpic5 = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int nezha = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int nezha_1 = 2130837639;
			
			// aapt resource value: 0x7f020095
			public const int piece_green = 2130837653;
			
			// aapt resource value: 0x7f020088
			public const int poemButton_selector = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int setting = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int setting_pressed = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int settingbg = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int settingButton = 2130837644;
			
			// aapt resource value: 0x7f02008d
			public const int sound_off = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int sound_on = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int splash = 2130837647;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080013
			public const int Game2_textlayout = 2131230739;
			
			// aapt resource value: 0x7f080003
			public const int LayoutGame1 = 2131230723;
			
			// aapt resource value: 0x7f080011
			public const int LayoutGame2 = 2131230737;
			
			// aapt resource value: 0x7f080045
			public const int LayoutLabel = 2131230789;
			
			// aapt resource value: 0x7f08001e
			public const int LayoutLabel1 = 2131230750;
			
			// aapt resource value: 0x7f080037
			public const int LayoutLabel2 = 2131230775;
			
			// aapt resource value: 0x7f080019
			public const int LayoutLabel3 = 2131230745;
			
			// aapt resource value: 0x7f080004
			public const int LayoutLabel4 = 2131230724;
			
			// aapt resource value: 0x7f08004b
			public const int LayoutLogo = 2131230795;
			
			// aapt resource value: 0x7f08003c
			public const int LotusBrand = 2131230780;
			
			// aapt resource value: 0x7f080036
			public const int LotusCulture = 2131230774;
			
			// aapt resource value: 0x7f08001d
			public const int LotusFamily = 2131230749;
			
			// aapt resource value: 0x7f080030
			public const int LotusFamily1 = 2131230768;
			
			// aapt resource value: 0x7f080032
			public const int LotusFamily2 = 2131230770;
			
			// aapt resource value: 0x7f080034
			public const int LotusFamily3 = 2131230772;
			
			// aapt resource value: 0x7f080000
			public const int LotusFood = 2131230720;
			
			// aapt resource value: 0x7f080040
			public const int LotusGame = 2131230784;
			
			// aapt resource value: 0x7f080050
			public const int LotusPoem = 2131230800;
			
			// aapt resource value: 0x7f08003b
			public const int buttonFood = 2131230779;
			
			// aapt resource value: 0x7f080039
			public const int buttonPoem = 2131230777;
			
			// aapt resource value: 0x7f080017
			public const int button_ok = 2131230743;
			
			// aapt resource value: 0x7f08003e
			public const int car_button = 2131230782;
			
			// aapt resource value: 0x7f080018
			public const int carlayout = 2131230744;
			
			// aapt resource value: 0x7f080049
			public const int galleryShow = 2131230793;
			
			// aapt resource value: 0x7f080042
			public const int game1_button = 2131230786;
			
			// aapt resource value: 0x7f080043
			public const int game2_button = 2131230787;
			
			// aapt resource value: 0x7f080014
			public const int game2_text = 2131230740;
			
			// aapt resource value: 0x7f08003a
			public const int horizontalScrollView1 = 2131230778;
			
			// aapt resource value: 0x7f08004c
			public const int imageButton1 = 2131230796;
			
			// aapt resource value: 0x7f08004d
			public const int imageButton2 = 2131230797;
			
			// aapt resource value: 0x7f08004e
			public const int imageButton3 = 2131230798;
			
			// aapt resource value: 0x7f08004f
			public const int imageButton4 = 2131230799;
			
			// aapt resource value: 0x7f080046
			public const int imageButtonBack = 2131230790;
			
			// aapt resource value: 0x7f08001f
			public const int imageButtonBack1 = 2131230751;
			
			// aapt resource value: 0x7f080031
			public const int imageButtonBack1_1 = 2131230769;
			
			// aapt resource value: 0x7f080033
			public const int imageButtonBack1_2 = 2131230771;
			
			// aapt resource value: 0x7f080035
			public const int imageButtonBack1_3 = 2131230773;
			
			// aapt resource value: 0x7f080038
			public const int imageButtonBack2 = 2131230776;
			
			// aapt resource value: 0x7f080001
			public const int imageButtonBack2_2 = 2131230721;
			
			// aapt resource value: 0x7f08003d
			public const int imageButtonBack3 = 2131230781;
			
			// aapt resource value: 0x7f08001a
			public const int imageButtonBack3_1 = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int imageButtonBack3_2 = 2131230748;
			
			// aapt resource value: 0x7f080041
			public const int imageButtonBack4 = 2131230785;
			
			// aapt resource value: 0x7f080005
			public const int imageButtonBack4_1 = 2131230725;
			
			// aapt resource value: 0x7f080012
			public const int imageButtonBack4_2 = 2131230738;
			
			// aapt resource value: 0x7f08006f
			public const int imageButtonBackSetting = 2131230831;
			
			// aapt resource value: 0x7f080047
			public const int imageButtonSetting = 2131230791;
			
			// aapt resource value: 0x7f080048
			public const int imageButtonSound = 2131230792;
			
			// aapt resource value: 0x7f08003f
			public const int jewelry_button = 2131230783;
			
			// aapt resource value: 0x7f08001b
			public const int jewelrylayout = 2131230747;
			
			// aapt resource value: 0x7f080002
			public const int linearLayout1 = 2131230722;
			
			// aapt resource value: 0x7f080044
			public const int linearLayoutMain = 2131230788;
			
			// aapt resource value: 0x7f080021
			public const int linearlayoutText1 = 2131230753;
			
			// aapt resource value: 0x7f08002d
			public const int logo1_button1 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int logo1_button2 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int logo1_button3 = 2131230767;
			
			// aapt resource value: 0x7f08006e
			public const int lotus_setting = 2131230830;
			
			// aapt resource value: 0x7f080007
			public const int piecebutton1 = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int piecebutton2 = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int piecebutton3 = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int piecebutton4 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int piecebutton5 = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int piecebutton6 = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int piecebutton7 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int piecebutton8 = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int piecebutton9 = 2131230735;
			
			// aapt resource value: 0x7f080020
			public const int scrollView1_logo1 = 2131230752;
			
			// aapt resource value: 0x7f080053
			public const int shi1 = 2131230803;
			
			// aapt resource value: 0x7f08005c
			public const int shi10 = 2131230812;
			
			// aapt resource value: 0x7f08005d
			public const int shi11 = 2131230813;
			
			// aapt resource value: 0x7f08005e
			public const int shi12 = 2131230814;
			
			// aapt resource value: 0x7f08005f
			public const int shi13 = 2131230815;
			
			// aapt resource value: 0x7f080060
			public const int shi14 = 2131230816;
			
			// aapt resource value: 0x7f080061
			public const int shi15 = 2131230817;
			
			// aapt resource value: 0x7f080062
			public const int shi16 = 2131230818;
			
			// aapt resource value: 0x7f080063
			public const int shi17 = 2131230819;
			
			// aapt resource value: 0x7f080064
			public const int shi18 = 2131230820;
			
			// aapt resource value: 0x7f080065
			public const int shi19 = 2131230821;
			
			// aapt resource value: 0x7f080054
			public const int shi2 = 2131230804;
			
			// aapt resource value: 0x7f080066
			public const int shi20 = 2131230822;
			
			// aapt resource value: 0x7f080067
			public const int shi21 = 2131230823;
			
			// aapt resource value: 0x7f080068
			public const int shi22 = 2131230824;
			
			// aapt resource value: 0x7f080069
			public const int shi23 = 2131230825;
			
			// aapt resource value: 0x7f08006a
			public const int shi24 = 2131230826;
			
			// aapt resource value: 0x7f08006b
			public const int shi25 = 2131230827;
			
			// aapt resource value: 0x7f08006c
			public const int shi26 = 2131230828;
			
			// aapt resource value: 0x7f08006d
			public const int shi27 = 2131230829;
			
			// aapt resource value: 0x7f080055
			public const int shi3 = 2131230805;
			
			// aapt resource value: 0x7f080056
			public const int shi4 = 2131230806;
			
			// aapt resource value: 0x7f080057
			public const int shi5 = 2131230807;
			
			// aapt resource value: 0x7f080058
			public const int shi6 = 2131230808;
			
			// aapt resource value: 0x7f080059
			public const int shi7 = 2131230809;
			
			// aapt resource value: 0x7f08005a
			public const int shi8 = 2131230810;
			
			// aapt resource value: 0x7f08005b
			public const int shi9 = 2131230811;
			
			// aapt resource value: 0x7f080006
			public const int tablelayout = 2131230726;
			
			// aapt resource value: 0x7f080027
			public const int textMain1 = 2131230759;
			
			// aapt resource value: 0x7f080028
			public const int textMain2 = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int textMain3 = 2131230761;
			
			// aapt resource value: 0x7f08002a
			public const int textMain4 = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int textMain5 = 2131230763;
			
			// aapt resource value: 0x7f08002c
			public const int textMain6 = 2131230764;
			
			// aapt resource value: 0x7f080052
			public const int textPoem = 2131230802;
			
			// aapt resource value: 0x7f080022
			public const int textTitle1 = 2131230754;
			
			// aapt resource value: 0x7f080023
			public const int textTitle2 = 2131230755;
			
			// aapt resource value: 0x7f080024
			public const int textTitle3 = 2131230756;
			
			// aapt resource value: 0x7f080025
			public const int textTitle4 = 2131230757;
			
			// aapt resource value: 0x7f080026
			public const int textTitle5 = 2131230758;
			
			// aapt resource value: 0x7f08004a
			public const int text_bless = 2131230794;
			
			// aapt resource value: 0x7f080016
			public const int text_input = 2131230742;
			
			// aapt resource value: 0x7f080051
			public const int text_poem_block = 2131230801;
			
			// aapt resource value: 0x7f080010
			public const int text_tucao = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int tip_text = 2131230741;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int food_list = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int game1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int game2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout3_1 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout3_2 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Logolayout1 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Logolayout1_1 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Logolayout1_2 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Logolayout1_3 = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Logolayout2 = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int Logolayout3 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int Logolayout4 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Main = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int poem_list = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int settinglayout = 2130903054;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int music = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int testmusic = 2131034113;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
